sudo: required
language: python
services: 
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: resolver-ng-ubuntu-1404
    - INSTANCE: resolver-ng-centos-7
    - INSTANCE: resolver-ng-ubuntu-1404-with-network-manager

script:
  - bundle exec kitchen verify ${INSTANCE}
